Leaflet example
bmesuere/belgium-topojson pull request #6
Opened 2020-06-04 01:35 UTC by JensTimmerman

I added an example to use this topojson data with leaflet by extending leaflet geojson's 
( inspired by http://bl.ocks.org/hpfast/2fb8de57c356d8c45ce511189eec5d6a and https://leafletjs.com/examples/choropleth/)

2020-06-04 10:13 UTC, bmesuere requested changes
Can you add a link to the example (and/or screenshot) to the main readme?

2020-08-26 13:29 UTC, JensTimmerman commented
@bmesuere added

2020-10-15 20:01 UTC, JensTimmerman commented
@bmesuere anything else that needs to be done here?

2026-09-21 20:04 UTC, JensTimmerman commented
@bmesuere Do you want me to change anything to get this merged in? or should I close the pr?

2026-09-22 16:31 UTC, closed without merging

2026-09-22 16:32 UTC, bmesuere commented
Thanks @JensTimmerman, I brought your example up to date and merged it in a separate PR #11 because I didn't want to write to your main branch. I kept your original commit in there.